// Frontend/front/src/FilterSearch.jsx
import React from "react";

const FilterSearch = ({ filter, setFilter, handleSubmit }) => {
    return (
        <div className="search">
            <form onSubmit={handleSubmit}>
                <input type="text" placeholder="Digite..." onChange={(e) => {setFilter(e.target.value)}}></input>
                <button type="submit">Buscar</button>
            </form>
        </div>
    )
};

export default FilterSearch;

// Frontend/vuejsfront/src/components/FilterSearch.vue
<template>
    <div className="filterSearch">
        <form @submit="handleSearch($event)">
            <input type="text" placeholder="Digite..." v-model="filter">
            <button type="submit">Buscar</button>
        </form>
    </div>
</template>

<script>
export default {
    name: 'FilterSearch',
    data() {
        return {
            filter: ''
        }
    },
    emits: ['applySearch'],
    methods: {
        handleSearch(e){
            e.preventDefault();
            this.$emit('applySearch', this.filter);
        }
    }
}
</script>
